##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.1.0] date: [Mon Nov 13 01:19:53 MSK 2023]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = AUDIS4BlouOff


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32f1xx_it.c \
Drivers/CMSIS/CM3/DeviceSupport/ST/STM32F10x/system_stm32f10x.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_adc.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_bkp.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_can.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_cec.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_crc.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_dac.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_dbgmcu.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_dma.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_exti.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_flash.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_fsmc.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_gpio.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_i2c.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_iwdg.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_pwr.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_rcc.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_rtc.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_sdio.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_spi.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_tim.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_usart.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/stm32f10x_wwdg.c \
Drivers/CMSIS/Device/ST/STM32F10x/src/misc.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f103x6.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DSTM32F103x6 \
-DUSE_STDPERIPH_DRIVER


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F1xx_HAL_Driver/Inc \
-IDrivers/STM32F1xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F1xx/Include \
-IDrivers/CMSIS/Device/ST/STM32F10x/inc \
-IDrivers/CMSIS/Device/ST/STM32F10x \
-IDrivers/CMSIS/CM3/DeviceSupport/ST/STM32F10x \
-IDrivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F103C6Tx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

#######################################
# FLash with ST-LINK
#######################################
stflash: $(BUILD_DIR)/$(TARGET).bin
	st-flash --reset write $< 0x8000000
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***